better documentation + final commit

diff --git a/Etapa7/Makefile b/Etapa7/Makefile
--- a/Etapa7/Makefile
+++ b/Etapa7/Makefile
@@ -33,11 +33,11 @@ target: $(PROJECT)
 
 .PHONY:
 
-.PHONY: optimizer
-optimizer: $(PROJECT)
+.PHONY: optimize
+optimize: $(PROJECT)
 	@if [ -z "$(FILE)" ]; then \
-		echo "Usage: make optimizer FILE=<input_file>"; \
-		echo "Example: make optimizer FILE=tests/io.2025++1"; \
+		echo "Usage: make optimize FILE=<input_file>"; \
+		echo "Example: make optimize FILE=tests/io.2025++1"; \
 		exit 1; \
 	fi
 	@if [ ! -f "$(FILE)" ]; then \
@@ -56,12 +56,41 @@ optimizer: $(PROJECT)
 			gcc -o "output/$${BASENAME}_optimized.out" "output/$${BASENAME}_optimized.s"; \
 			if [ $$? -eq 0 ]; then \
 				echo "- Binary code saved at output/$${BASENAME}_optimized.out"; \
-				echo "\nTest completed successfully for $$BASENAME."; \
+				echo "\nCompilation completed successfully for $(FILE)."; \
 			else \
 				echo "- Error: Failed to generate optimized binary code."; \
 			fi; \
 		else \
 			echo "- Error: Failed to generate original binary code."; \
+		fi \
+	else \
+		echo "- Error: Compilation failed."; \
+	fi
+
+.PHONY: test
+test: $(PROJECT)
+	@if [ -z "$(FILE)" ]; then \
+		echo "Usage: make test FILE=<input_file>"; \
+		echo "Example: make test FILE=tests/io.2025++1"; \
+		exit 1; \
+	fi
+	@if [ ! -f "$(FILE)" ]; then \
+		echo "Error: File '$(FILE)' not found."; \
+		exit 1; \
+	fi
+	@mkdir -p output
+	@BASENAME=$$(basename "$(FILE)" .2025++1); \
+	./$(PROJECT) "$(FILE)" "output/$${BASENAME}_symbol_table.txt" "output/$${BASENAME}_AST.txt" "output/$${BASENAME}_decompiled.txt" "output/$${BASENAME}_TAC.txt" "output/$${BASENAME}.s"; \
+	if [ $$? -eq 0 ]; then \
+		echo "\nGenerating binary code:"; \
+		gcc -o "output/$${BASENAME}.out" "output/$${BASENAME}.s"; \
+		if [ $$? -eq 0 ]; then \
+			echo "- Binary code saved at output/$${BASENAME}.out"; \
+			echo "\nRunning the program:"; \
+			./output/$${BASENAME}.out; \
+			echo "- Test completed successfully for $$BASENAME."; \
+		else \
+			echo "- Error: Failed to generate binary code."; \
 		fi \
 	else \
 		echo "- Error: Compilation failed."; \
